/* Generated By:JavaCC: Do not edit this line. EG1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONTAINMENT = 5;
  /** RegularExpression Id. */
  int ACTION = 6;
  /** RegularExpression Id. */
  int DATABUF = 7;
  /** RegularExpression Id. */
  int OPENBRACKET = 8;
  /** RegularExpression Id. */
  int CLOSEBRACKET = 9;
  /** RegularExpression Id. */
  int TERMINATOR = 10;
  /** RegularExpression Id. */
  int TYPE = 11;
  /** RegularExpression Id. */
  int NAME = 12;
  /** RegularExpression Id. */
  int SYMBOL = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Containment\"",
    "\"action\"",
    "\"data_buff\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "<TYPE>",
    "<NAME>",
    "<SYMBOL>",
  };

}
